Repository thoth-station/s2i, pull requests merged in 2020-05, with the labels that each got.

#35 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/XS

#30 Import image before the build is triggered
  thoth/s2i/cli.py
Labels: approved

#36 Fix message produce to match actual option provided
  thoth/s2i/cli.py
  thoth/s2i/lib.py
  thoth/s2i/objs.py
Labels: approved, size/L

#38 Release of version 0.1.2
  thoth/s2i/__init__.py
Labels: bot, size/XS

#39 Fix README file causing failures in PyPI releases
  README.rst
Labels: approved, size/XS

#40 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/S
