Repository thoth-station/s2i, pull requests merged in 2020-02, with the labels that each got.

#1 Initial project import
  .thoth.yaml
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  README.md
  README.rst
  mypy.ini
  requirements.txt
  setup.py
  tests/base.py
  tests/data/template/bc/bc.yaml
  tests/data/template/bc/list.yaml
  tests/data/template/bc/template.yaml
  tests/data/template/is/is.yaml
  tests/data/template/is/list.yaml
  tests/data/template/is/template.yaml
  tests/test_objs.py
  thoth-s2i
  thoth/s2i/__init__.py
  thoth/s2i/cli.py
  thoth/s2i/exceptions.py
  thoth/s2i/helpers.py
  thoth/s2i/lib.py
  thoth/s2i/objs.py
  thoth/s2i/py.typed
Labels: approved, do-not-merge/needs-rebase, size/XXL

#4 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#5 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M
