Repository thoth-station/s2i, pull requests merged in 2020-04, with the labels that each got.

#17 No build to trigger
  .zuul.yaml
Labels: approved

#11 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/S

#14 Automatic update of dependency pytest from 5.3.5 to 5.4.1
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/S

#15 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase, size/S

#18 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/S

#19 Automatic update of dependency pytest-mypy from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot, size/M

#20 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#22 Release of version 0.1.0
  thoth/s2i/__init__.py
Labels: bot, size/XS

#23 Image stream tag does not need to be provided
  thoth/s2i/lib.py
Labels: approved, size/XS

#24 Do not insert path to config file
  thoth/s2i/objs.py
Labels: approved, size/XS

#25 Provide requirements format explicitly
  thoth/s2i/objs.py
Labels: approved, size/XS

#27 Release of version 0.1.1
  thoth/s2i/__init__.py
Labels: bot, size/XS

#28 Long description is reStructuredText
  setup.py
Labels: approved, size/XS

#29 Include requirements.txt
  MANIFEST.in
Labels: approved, size/XS

#31 Discard image tag before checking image availability
  thoth/s2i/cli.py
Labels: approved, size/XS

#32 Pass Thoth specific environment variables to the build config
  thoth/s2i/cli.py
  thoth/s2i/objs.py
Labels: approved, size/S

#33 Remove ENABLE_PIPENV environment variable
  thoth/s2i/objs.py
Labels: approved, size/XS

#34 point to right urls
  README.rst
Labels: approved, size/XS
